package com.opsfactor.community.capability.supplyplanning.configuration.facade.mapper;

import com.opsfactor.community.capability.supplyplanning.configuration.facade.dto.PerfilExecucaoSupplyPlanDTO;
import com.opsfactor.community.capability.supplyplanning.configuration.domain.PerfilExecucaoSupplyPlan;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

/**
 * Mapper Community do perfil de execucao Supply Planning.
 *
 * <p>Campos Enterprise sao devolvidos como defaults neutros para que o front
 * compartilhado consiga marcar/bloquear controles. O `executionModel` e
 * sempre `HEURISTICO` no Community; o Enterprise deve fornecer mapper/service
 * proprio quando reintroduzir otimizador e process chain.</p>
 */
@Mapper(componentModel = "spring")
public interface PerfilExecucaoSupplyPlanAutoMapper {
    
    @Mapping(source = "descricao", target = "description")
    @Mapping(target = "materialFilterId", expression = "java(null)")
    @Mapping(target = "executionModel", expression = "java(com.opsfactor.community.capability.supplyplanning.configuration.domain.PerfilExecucaoSupplyPlan.ModoExecucao.HEURISTICO)")
    @Mapping(target = "customerOrdersAndForecastReconciliationModelForProjectedInventory", expression = "java(null)")
    @Mapping(target = "customerOrdersAndForecastReconciliationModelForSafetyStock", expression = "java(null)")
    @Mapping(target = "optimizationModelType", expression = "java(null)")
    @Mapping(target = "customerOrderHorizonInDays", expression = "java(null)")
    @Mapping(target = "demandPlanMetDemandImpactCoefficient", expression = "java(null)")
    @Mapping(target = "customerOrderMetDemandImpactCoefficient", expression = "java(null)")
    @Mapping(target = "increaseObjectiveFunctionImpactInEarlierPeriods", expression = "java(false)")
    @Mapping(target = "maximumPercentageIncreaseObjectiveFunctionImpactAtFirstPeriod", expression = "java(null)")
    @Mapping(target = "objectiveFunctionTemporalImpactDecayModel", expression = "java(null)")
    @Mapping(target = "objectiveFunctionTemporalImpactExponentialDecayFactor", expression = "java(null)")
    @Mapping(target = "objectiveFunctionTemporalImpactMinimumMultiplier", expression = "java(null)")
    @Mapping(target = "customerDemandPrioritizationModelId", expression = "java(null)")
    @Mapping(target = "safetyStockPrioritizationModelId", expression = "java(null)")
    @Mapping(source = "geraRequisicoesInbound", target = "generatePlannedInboundOrders")
    @Mapping(source = "geraOrdensProducaoPlanejadas", target = "generatePlannedProductionOrders")
    @Mapping(source = "trataPoliticaEstoqueComoDrp", target = "alwaysUseDrp")
    @Mapping(expression = "java(perfilExecucaoSupplyPlan.getHorizontePlanoDiasCadastrado())", target = "planHorizonInDays")
    @Mapping(target = "considerForecastForMto", expression = "java(true)")
    @Mapping(source = "encadeiaExecucaoPlanoRestrito", target = "automaticallyRunConstrainedPlan")
    @Mapping(source = "arredondaRequisicoesLoteMinimoEMultiplo", target = "roundRequisitionsByMoqAndLotSize")
    @Mapping(expression = "java(perfilExecucaoSupplyPlan.getArredondaRequisicoesLoteMinimoEMultiploEmTodosPeriodosExpedicao())", target = "roundRequisitionsByMoqAndLotSizeForAllExpeditionPeriods")
    @Mapping(expression = "java(perfilExecucaoSupplyPlan.getNumeroPeriodosExpedicaoArredondaRequisicoesLoteMinimoEMultiplo())", target = "expeditionPeriodsToRoundRequisitionsByMoqAndLotSize")
    @Mapping(target = "roundPlannedPurchaseOrdersByMinimumLotSize", expression = "java(false)")
    @Mapping(target = "allocateTransfersInFleets", expression = "java(false)")
    @Mapping(source = "arredondaProducaoLoteMinimoEMultiplo", target = "roundProductionByMoqAndLotSize")
    @Mapping(expression = "java(perfilExecucaoSupplyPlan.getArredondaProducaoLoteMinimoEMultiploEmTodosPeriodos())", target = "roundProductionByMoqAndLotSizeForAllPeriods")
    @Mapping(expression = "java(perfilExecucaoSupplyPlan.getNumeroPeriodosArredondaProducaoLoteMinimoEMultiplo())", target = "periodsToRoundProductionByMoqAndLotSize")
    @Mapping(target = "considerSelloutOrdersBacklog", expression = "java(false)")
    @Mapping(target = "considerSelloutOrdersFuture", expression = "java(false)")
    @Mapping(target = "considerSellinOrdersBacklog", expression = "java(false)")
    @Mapping(target = "considerSellinOrdersFuture", expression = "java(false)")
    @Mapping(target = "considerTransferOrdersBacklog", expression = "java(false)")
    @Mapping(target = "considerTransferOrdersFuture", expression = "java(false)")
    @Mapping(target = "considerPurchaseOrdersBacklog", expression = "java(false)")
    @Mapping(target = "considerPurchaseOrdersFuture", expression = "java(false)")
    @Mapping(target = "considerProductionOrdersBacklog", expression = "java(false)")
    @Mapping(target = "considerProductionOrdersFuture", expression = "java(false)")
    @Mapping(target = "enableDemandCatchUpFromPastSellout", expression = "java(false)")
    @Mapping(target = "allowBacklogCarryOver", expression = "java(false)")
    @Mapping(target = "forceMakeToOrderModel", expression = "java(false)")
    @Mapping(source = "consideraEstoqueInicial", target = "considerInitialStock")
    @Mapping(target = "saveOptimizerVariablesAndConstraints", expression = "java(false)")
    @Mapping(source = "salvaInventoryPlan", target = "saveInventoryPlan")
    @Mapping(target = "saveConstraintBacktracking", expression = "java(false)")
    @Mapping(target = "executeSupplyPlanForAllLocations", expression = "java(true)")
    @Mapping(source = "modeloEstoqueTarget", target = "targetStockModel")
    @Mapping(source = "geraPlanoIrrestrito", target = "generateUnconstrainedPlan")
    @Mapping(source = "ignoraRestricaoProducaoIrrestrito", target = "ignoreProductionConstraintsForUnconstrainedPlan")
    @Mapping(target = "ignoreStorageConstraintsForUnconstrainedPlan", expression = "java(false)")
    @Mapping(target = "ignoreOutboundConstraintsForUnconstrainedPlan", expression = "java(false)")
    @Mapping(target = "ignoreInboundConstraintsForUnconstrainedPlan", expression = "java(false)")
    @Mapping(target = "ignoreLeadTimeConstraintsForUnconstrainedPlan", expression = "java(false)")
    @Mapping(target = "maximumTransferCostImpactForLeadTimeReduction", expression = "java(null)")
    @Mapping(target = "maximumMaterialObjectiveValueImpactForLeadTimeReduction", expression = "java(null)")
    @Mapping(target = "ignoreMarginConstraintsForUnconstrainedPlan", expression = "java(false)")
    @Mapping(target = "metDemandObjectiveValueIncreasePercentage", expression = "java(null)")
    @Mapping(target = "minimumMetDemandObjectiveValue", expression = "java(null)")
    @Mapping(target = "generatePL", expression = "java(false)")
    @Mapping(target = "associateSalesToInputMaterialsInRetroaction", expression = "java(false)")
    @Mapping(source = "generateProfitLoss", target = "generateProfitLoss")
    @Mapping(source = "allowSalesProfitLossBomRetroaction", target = "allowSalesProfitLossBomRetroaction")
    @Mapping(target = "optimizationUom", expression = "java(null)")
    @Mapping(target = "salesMeasure", expression = "java(null)")
    @Mapping(target = "taxApportionmentModel", expression = "java(null)")
    @Mapping(target = "unitValueByOptimizationUom", expression = "java(null)")
    @Mapping(target = "considerLocationFixedCost", expression = "java(false)")
    @Mapping(target = "considerProductionResourceFixedCost", expression = "java(false)")
    @Mapping(target = "considerStorageCost", expression = "java(false)")
    @Mapping(target = "considerTransferCost", expression = "java(false)")
    @Mapping(target = "considerTaxesInTransportationLines", expression = "java(false)")
    @Mapping(target = "considerInboundOutboundCosts", expression = "java(false)")
    @Mapping(target = "considerProductionCost", expression = "java(false)")
    @Mapping(target = "considerSupplierPrices", expression = "java(false)")
    @Mapping(target = "estimateUnitCogsForWorkingCapitalAndInventoryPolicy", expression = "java(false)")
    @Mapping(source = "consideraRestricaoProducao", target = "considerProductionConstraints")
    @Mapping(target = "considerStorageConstraints", expression = "java(false)")
    @Mapping(target = "considerInboundConstraints", expression = "java(false)")
    @Mapping(target = "considerOutboundConstraints", expression = "java(false)")
    @Mapping(target = "aiOptimizer", expression = "java(com.opsfactor.community.capability.supplyplanning.configuration.domain.PerfilExecucaoSupplyPlan.OtimizadorInteligenciaArtificial.DESABILITADO)")
    @Mapping(target = "directDemandFairShare", expression = "java(true)")
    @Mapping(target = "numberSegmentsDirectDemandGapLinearization", expression = "java(null)")
    @Mapping(target = "fairShareMaximumPercentagePenaltyUnmetDemand", expression = "java(null)")
    @Mapping(target = "fairShareMaximumPercentagePenaltySafetyStockGap", expression = "java(null)")
    @Mapping(target = "safetyStockFairShare", expression = "java(false)")
    @Mapping(target = "numberSegmentsSafetyStockGapLinearization", expression = "java(null)")
    @Mapping(target = "workingCapitalPercentualCost", expression = "java(null)")
    @Mapping(target = "allowStockAtClients", expression = "java(false)")
    @Mapping(target = "allowStockAtTransshipmentPoints", expression = "java(false)")
    @Mapping(source = "locationsClienteApenasPropagamDemanda", target = "consolidateClientDemand")
    @Mapping(source = "modoPropagacaoDemanda", target = "demandConsolidationMode")
    @Mapping(target = "enableLineSequencing", expression = "java(false)")
    @Mapping(target = "enableGreenfieldBrownfield", expression = "java(false)")
    @Mapping(target = "maximumOptimizerExecutionTime", expression = "java(null)")
    @Mapping(target = "softTargetMaximumPercentPenalty", expression = "java(null)")
    @Mapping(target = "softTargetDeviationAmplitudeAsTargetPercent", expression = "java(null)")
    @Mapping(target = "softTargetDeviationLinearizationNumberSegments", expression = "java(null)")
    @Mapping(target = "firmOrderCogsIncentivePercentage", expression = "java(null)")
    @Mapping(source = "geraRequisicoesInboundParaMateriaisComProducaoViavel", target = "generatePlannedInboundOrdersWhenProductionIsViable")
    @Mapping(target = "safetyStockGapPercentualCost", expression = "java(null)")
    @Mapping(target = "segmentInventoryByBatch", expression = "java(false)")
    @Mapping(target = "increaseWorkingCapitalImpactForOlderBatches", expression = "java(false)")
    @Mapping(target = "maximumPercentageIncreaseWorkingCapitalImpactForOldestBatch", expression = "java(null)")
    @Mapping(expression = "java(perfilExecucaoSupplyPlan.getSetPerfilExecucaoPoliticaEstoques().stream().map(x -> x.getPoliticaEstoques().getId()).collect(java.util.stream.Collectors.toSet()))", target = "inventoryPolicyIdSet")
    @Mapping(target = "temporalSplitCurveIdSet", expression = "java(new java.util.HashSet<>())")
    @Mapping(target = "generateProductionScheduling", expression = "java(false)")
    @Mapping(target = "generateDetailedPlan", expression = "java(false)")
    @Mapping(target = "detailedPlanBucketSize", expression = "java(null)")
    @Mapping(target = "detailedPlanPlanningHorizonInBuckets", expression = "java(null)")
    @Mapping(target = "productiveCapacityType", expression = "java(com.opsfactor.community.capability.supplyplanning.configuration.domain.PerfilExecucaoSupplyPlan.TipoCapacidadeProdutiva.HORAS_POR_DIA)")
    @Mapping(target = "logisticsCapacityLevel", expression = "java(null)")
    @Mapping(source = "tipoPlanoTrabalho", target = "planTypeForWorkVersion")
    @Mapping(target = "penalizeUnmetDemand", expression = "java(false)")
    @Mapping(target = "unmetDemandPenalizationAsFractionOfGrossSales", expression = "java(null)")
    @Mapping(target = "unmetDemandPenalizationAsUnitImpact", expression = "java(null)")
    @Mapping(target = "unmetDemandPenalizationAsUnitImpactUomId", expression = "java(null)")
    @Mapping(target = "logisticsCostCurvesId", expression = "java(null)")
    @Mapping(target = "applyFreightCostCurves", expression = "java(false)")
    @Mapping(target = "applyLocationCostCurves", expression = "java(false)")
    public PerfilExecucaoSupplyPlanDTO converte(PerfilExecucaoSupplyPlan perfilExecucaoSupplyPlan);

    @Mapping(source = "description", target = "descricao")
    @Mapping(target = "materialFilterId", ignore = true)
    @Mapping(source = "generatePlannedInboundOrders", target = "geraRequisicoesInbound")
    @Mapping(source = "generatePlannedProductionOrders", target = "geraOrdensProducaoPlanejadas")
    @Mapping(source = "alwaysUseDrp", target = "trataPoliticaEstoqueComoDrp")
    @Mapping(source = "planHorizonInDays", target = "horizontePlanoDias")
    @Mapping(source = "automaticallyRunConstrainedPlan", target = "encadeiaExecucaoPlanoRestrito")
    @Mapping(source = "roundRequisitionsByMoqAndLotSize", target = "arredondaRequisicoesLoteMinimoEMultiplo")
    @Mapping(source = "roundRequisitionsByMoqAndLotSizeForAllExpeditionPeriods", target = "arredondaRequisicoesLoteMinimoEMultiploEmTodosPeriodosExpedicao")
    @Mapping(source = "expeditionPeriodsToRoundRequisitionsByMoqAndLotSize", target = "numeroPeriodosExpedicaoArredondaRequisicoesLoteMinimoEMultiplo")
    @Mapping(source = "roundProductionByMoqAndLotSize", target = "arredondaProducaoLoteMinimoEMultiplo")
    @Mapping(source = "roundProductionByMoqAndLotSizeForAllPeriods", target = "arredondaProducaoLoteMinimoEMultiploEmTodosPeriodos")
    @Mapping(source = "periodsToRoundProductionByMoqAndLotSize", target = "numeroPeriodosArredondaProducaoLoteMinimoEMultiplo")
    @Mapping(source = "considerInitialStock", target = "consideraEstoqueInicial")
    @Mapping(source = "saveInventoryPlan", target = "salvaInventoryPlan")
    @Mapping(source = "considerProductionConstraints", target = "consideraRestricaoProducao")
    @Mapping(source = "targetStockModel", target = "modeloEstoqueTarget")
    @Mapping(source = "generateUnconstrainedPlan", target = "geraPlanoIrrestrito")
    @Mapping(source = "ignoreProductionConstraintsForUnconstrainedPlan", target = "ignoraRestricaoProducaoIrrestrito")
    @Mapping(target = "aplicaFairShareDemandaDireta", expression = "java(true)")
    @Mapping(source = "consolidateClientDemand", target = "locationsClienteApenasPropagamDemanda")
    @Mapping(source = "demandConsolidationMode", target = "modoPropagacaoDemanda")
    @Mapping(source = "generatePlannedInboundOrdersWhenProductionIsViable", target = "geraRequisicoesInboundParaMateriaisComProducaoViavel")
    @Mapping(source = "planTypeForWorkVersion", target = "tipoPlanoTrabalho")
    @Mapping(source = "generateProfitLoss", target = "generateProfitLoss")
    @Mapping(source = "allowSalesProfitLossBomRetroaction", target = "allowSalesProfitLossBomRetroaction")
    @Mapping(target = "allowBacklogCarryOver", expression = "java(false)")
    @Mapping(target = "enableDemandCatchUpFromPastSellout", expression = "java(false)")
    @Mapping(target = "enableLineSequencing", expression = "java(false)")
    @Mapping(target = "enableGreenfieldBrownfield", expression = "java(false)")
    public PerfilExecucaoSupplyPlan converte(PerfilExecucaoSupplyPlanDTO perfilExecucaoSupplyPlanDTO);
        
    public List<PerfilExecucaoSupplyPlanDTO> converteListaEntidadesParaDTOs(List<PerfilExecucaoSupplyPlan> perfilExecucaoSupplyPlanList);
    
    public List<PerfilExecucaoSupplyPlan> converteListaDTOsParaEntidade(List<PerfilExecucaoSupplyPlanDTO> perfilExecucaoSupplyPlanDTOList);
    
}
